name: jetkvm-cloud-api

networks:
  jetkvm:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: jetkvm
      POSTGRES_USER: jetkvm
      POSTGRES_DB: jetkvm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jetkvm -d jetkvm"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - jetkvm
    volumes:
      - postgresql:/var/lib/postgresql

  app: &app
    build: .
    environment:
      PORT: 5172
      DATABASE_URL: postgres://jetkvm:jetkvm@db:5432/jetkvm
    depends_on:
      db:
        condition: service_healthy
    ports:
        - "5172:5172"
    networks:
      - jetkvm

  # Trigger prisma migration
  # This can be done in the app container as well, but is generally discouraged.
  app-migrate:
    <<: *app
    command: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy"]
    ports: []
    restart: no

volumes:
  postgresql:
    driver: local
